"""
TickerService – Loads US stock/ETF tickers from a local JSON file
(data/tickers.json) and serves fast autocomplete search to the UI.

The JSON file is generated by download_tickers.py using Polygon's
reference endpoint.  Re-run that script periodically to pick up
new listings / delistings.
"""
import json
import logging
from pathlib import Path

logger = logging.getLogger("optionsganster")

_DATA_FILE = Path(__file__).resolve().parent.parent / "data" / "tickers.json"


class TickerService:
    """In-memory ticker directory loaded from a local JSON file."""

    def __init__(self):
        self._tickers: list[dict] = []   # [{symbol, name, type, name_upper}]
        self._loaded: bool = False

    # ── public API ──────────────────────────────────────────

    @property
    def ready(self) -> bool:
        return self._loaded

    def load(self):
        """Load tickers from data/tickers.json.  Called once at startup."""
        if self._loaded:
            return
        try:
            raw: list[dict] = json.loads(_DATA_FILE.read_text())
            self._tickers = [
                {
                    "symbol": t["s"],
                    "name": t["n"],
                    "type": "ETF" if t["t"] == "E" else "Stock",
                    "name_upper": t["n"].upper(),
                }
                for t in raw
            ]
            self._loaded = True
            print(f"[TickerService] Loaded {len(self._tickers)} tickers from {_DATA_FILE.name}")
        except FileNotFoundError:
            print(f"[TickerService] {_DATA_FILE} not found — run download_tickers.py first")
            self._tickers = self._fallback_tickers()
            self._loaded = True
            print(f"[TickerService] Using {len(self._tickers)} fallback tickers")
        except Exception as e:
            print(f"[TickerService] Error loading tickers: {e}")
            self._tickers = self._fallback_tickers()
            self._loaded = True

    def search(self, query: str, limit: int = 20) -> list[dict]:
        """Fast prefix / substring search, prioritises exact-prefix matches."""
        if not self._loaded:
            self.load()
        if not query:
            return self._tickers[:limit]
        q = query.upper()
        exact: list[dict] = []
        prefix: list[dict] = []
        contains: list[dict] = []
        for t in self._tickers:
            sym = t["symbol"]
            if sym == q:
                exact.append(t)
            elif sym.startswith(q):
                prefix.append(t)
            elif q in sym or q in t["name_upper"]:
                if len(contains) < limit * 3:
                    contains.append(t)
        # exact first, then prefix, then substring
        results = exact + prefix
        remaining = limit - len(results)
        if remaining > 0:
            results.extend(contains[:remaining])
        return results[:limit]

    # ── Fallback ────────────────────────────────────────────

    @staticmethod
    def _fallback_tickers() -> list[dict]:
        """Hardcoded popular tickers in case the JSON file is missing."""
        names = {
            "QQQ": "Invesco QQQ Trust", "SPY": "SPDR S&P 500 ETF",
            "IWM": "iShares Russell 2000 ETF", "DIA": "SPDR Dow Jones ETF",
            "AAPL": "Apple Inc", "MSFT": "Microsoft Corp", "GOOGL": "Alphabet Inc",
            "AMZN": "Amazon.com Inc", "NVDA": "NVIDIA Corp", "META": "Meta Platforms",
            "TSLA": "Tesla Inc", "AMD": "Advanced Micro Devices",
            "NFLX": "Netflix Inc", "CRM": "Salesforce Inc",
            "INTC": "Intel Corp", "BA": "Boeing Co", "JPM": "JPMorgan Chase",
            "V": "Visa Inc", "MA": "Mastercard Inc",
            "DIS": "Walt Disney Co", "PYPL": "PayPal Holdings",
            "SQ": "Block Inc", "SHOP": "Shopify Inc", "COIN": "Coinbase Global",
            "PLTR": "Palantir Technologies", "SOFI": "SoFi Technologies",
            "SNAP": "Snap Inc", "ROKU": "Roku Inc", "NET": "Cloudflare Inc",
            "ARM": "Arm Holdings", "SMCI": "Super Micro Computer",
            "AVGO": "Broadcom Inc", "MU": "Micron Technology",
            "TQQQ": "ProShares UltraPro QQQ", "SQQQ": "ProShares UltraPro Short QQQ",
        }
        etfs = {"QQQ", "SPY", "IWM", "DIA", "TQQQ", "SQQQ"}
        return [
            {"symbol": s, "name": n, "type": "ETF" if s in etfs else "Stock", "name_upper": n.upper()}
            for s, n in sorted(names.items())
        ]


# Singleton
ticker_service = TickerService()
